# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Masonry-UIScrollerView' do

   pod "Masonry"
   pod 'ReactiveCocoaLayout'
  target 'Masonry-UIScrollerViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Masonry-UIScrollerViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
