# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MasonryDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod "Masonry"
  # Pods for MasonryDemo

  target 'MasonryDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MasonryDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
